### PR TITLE
Gradle 7.1.1 compat

### PR DESCRIPTION
**Pull request by jhyry-gcpud**
Fix for compatibility with Gradle 7.1.1.

### CODE REVIEW

**Comment by eerohele** [comment]
There's a bunch of changes here that don't seem related to Gradle 7.1.1 compatibility. The Eclipse stuff, for instance.

Can you explain how the plugin currently isn't compatible with Gradle 7.1.1 and how the changes here fix it?

**Comment by jhyry-gcpud** [comment]
@eerohele  Good point. I can remove that stuff. I have the following list of changes required to make the build compatible with Gradle 7+:
- Wrapper upgrade:
    ```
    diff --git a/build.gradle b/build.gradle
    index 4fe96db..03449b4 100644
    --- a/build.gradle
    +++ b/build.gradle
    @@ -33,7 +31,7 @@ test {
     }
    
     wrapper {
    -    gradleVersion = '6.0'
    +    gradleVersion = '7.1.1'
     }
    
     codenarc {
    
    diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
    index 35cfa32..05679dc 100644
    --- a/gradle/wrapper/gradle-wrapper.properties
    +++ b/gradle/wrapper/gradle-wrapper.properties
    @@ -1,6 +1,5 @@
    -#Tue Nov 12 23:08:13 EET 2019
     distributionBase=GRADLE_USER_HOME
     distributionPath=wrapper/dists
    +distributionUrl=https\://services.gradle.org/distributions/gradle-7.1.1-bin.zip
     zipStoreBase=GRADLE_USER_HOME
     zipStorePath=wrapper/dists
    -distributionUrl=https\://services.gradle.org/distributions/gradle-6.0-all.zip
    ```
- Gradle 7+ uses Groovy 3, which is incompatible with the version of Spock this project is using, thus the Spock upgrade to a compatible version:
    image
- A workaround is required to get the prepareResources task to complete successfully.
    The reason for the following workaround is described [here](https://discuss.gradle.org/t/gradle-7-fail-for-duplicates-in-copy-specs-has-no-duplicates-in-project/39834) and [here](https://github.com/gradle/gradle/issues/17236):
    ```
    // Temporary workaround for phantom duplicates in Gradle 7+.
    rootProject.tasks.named("processResources") {
         duplicatesStrategy = 'include'
    }
    ```

Let me know if this is sufficient information or not.
Thanks so much for taking a look at this!

Jon

**Comment by jhyry-gcpud** [comment]
The result of running the build on 7.1.1 is the following, with --no-build-cache and --rerun-tasks to ensure everything works:
```
PS saxon-gradle> ./gradlew clean build --no-build-cache --rerun-tasks

> Task :groovydoc
Trying to override old definition of task fileScanner
The Cobertura XML file [null] is not accessible; skipping this rule
The Cobertura XML file [null] is not accessible; skipping this rule

BUILD SUCCESSFUL in 33s
15 actionable tasks: 15 executed
```
Here's the build result:
[saxon-gradle_7.1.1_build.zip](https://github.com/eerohele/saxon-gradle/files/6910436/saxon-gradle_7.1.1_build.zip)

**Comment by jhyry-gcpud** [comment]
In regard to src/main/groovy/com/github/eerohele/SaxonXsltTask.groovy, the plugin would not build in 7.1.1 without the added annotations and getters.

**Comment by jhyry-gcpud** [comment]
@eerohele  Is this PR ok now?

**Comment by eerohele** [comment]
@jhyry-gcpud Sorry for the delay. Life keeps getting in the way.

I looked into it a bit, and [I think I fixed most of the Gradle 7 compatibility issues](https://github.com/eerohele/saxon-gradle/compare/e222d55f03f3bcf2b4424d16d6460e9660009515...64683066937b90383ae5369ca4312343b044166b). I've published v0.9.0-beta4 into the Gradle plugin portal if you want to give it a try.

After these changes, I don't get any deprecation warnings regarding the `@Input` or `@Internal` stuff. If there's a problem that requires them to be added that you'd like to get fixed, please make a new PR that only adds those attributes, with an explanation of the problem it fixes.

**Comment by jhyry-gcpud** [comment]
I very much understand life getting in the way.
Thanks again so much for looking at this and working out the underlying issues, I can most definitely give this a try sometime in the next week or 2.
Cheers!

**Comment by jhyry-gcpud** [comment]
@eerohele Works like a charm! Thanks again!

**Comment by eerohele** [comment]
Cool, thanks for reporting back!

**Pull request closed without merging**
